{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyPEJ1XcNG4VJ/oN6AQnzVO5",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/mallellysastha/Data_preprocessing/blob/main/f1.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 5,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "4bipu_pL925A",
        "outputId": "0fc36a6b-700d-4653-f4cb-9425012a30d2"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Dataset Shape:\n",
            "(10, 5)\n",
            "\n",
            "Columns:\n",
            "Index(['driver_name', 'age', 'team', 'circuit', 'lap_time_seconds'], dtype='object')\n",
            "\n",
            "Dataset Info:\n",
            "<class 'pandas.core.frame.DataFrame'>\n",
            "RangeIndex: 10 entries, 0 to 9\n",
            "Data columns (total 5 columns):\n",
            " #   Column            Non-Null Count  Dtype  \n",
            "---  ------            --------------  -----  \n",
            " 0   driver_name       10 non-null     object \n",
            " 1   age               9 non-null      float64\n",
            " 2   team              10 non-null     object \n",
            " 3   circuit           10 non-null     object \n",
            " 4   lap_time_seconds  10 non-null     float64\n",
            "dtypes: float64(2), object(3)\n",
            "memory usage: 532.0+ bytes\n",
            "None\n",
            "\n",
            "Missing Values:\n",
            "driver_name         0\n",
            "age                 1\n",
            "team                0\n",
            "circuit             0\n",
            "lap_time_seconds    0\n",
            "dtype: int64\n",
            "\n",
            "Duplicates Before: 0\n",
            "Duplicates After: 0\n",
            "\n",
            "Outliers Removed\n",
            "\n",
            "Data Types:\n",
            "driver_name          object\n",
            "age                 float64\n",
            "team                 object\n",
            "circuit              object\n",
            "lap_time_seconds    float64\n",
            "dtype: object\n",
            "\n",
            "After Encoding:\n",
            "       driver_name  age  lap_time_seconds  team_Aston Martin  team_Ferrari  \\\n",
            "0   Lewis Hamilton   38              85.5              False         False   \n",
            "1   Max Verstappen   26              82.1              False         False   \n",
            "2  Charles Leclerc   31              84.9              False          True   \n",
            "3     Sergio Perez   34              83.2              False         False   \n",
            "4   George Russell   25              86.0              False         False   \n",
            "\n",
            "   team_McLaren  team_Mercedes  team_Red Bull  circuit_Silverstone  \\\n",
            "0         False           True          False                False   \n",
            "1         False          False           True                 True   \n",
            "2         False          False          False                False   \n",
            "3         False          False           True                False   \n",
            "4         False           True          False                 True   \n",
            "\n",
            "   circuit_Spa  \n",
            "0        False  \n",
            "1        False  \n",
            "2        False  \n",
            "3         True  \n",
            "4        False  \n",
            "\n",
            "After Scaling:\n",
            "       driver_name       age  lap_time_seconds  team_Aston Martin  \\\n",
            "0   Lewis Hamilton  1.253566          0.947502              False   \n",
            "1   Max Verstappen -0.797724         -1.688276              False   \n",
            "2  Charles Leclerc  0.056980          0.482364              False   \n",
            "3     Sergio Perez  0.569803         -0.835524              False   \n",
            "4   George Russell -0.968665          1.335116              False   \n",
            "\n",
            "   team_Ferrari  team_McLaren  team_Mercedes  team_Red Bull  \\\n",
            "0         False         False           True          False   \n",
            "1         False         False          False           True   \n",
            "2          True         False          False          False   \n",
            "3         False         False          False           True   \n",
            "4         False         False           True          False   \n",
            "\n",
            "   circuit_Silverstone  circuit_Spa  \n",
            "0                False        False  \n",
            "1                 True        False  \n",
            "2                False        False  \n",
            "3                False         True  \n",
            "4                 True        False  \n",
            "\n",
            "After Removing Driver Name Column:\n",
            "        age  lap_time_seconds  team_Aston Martin  team_Ferrari  team_McLaren  \\\n",
            "0  1.253566          0.947502              False         False         False   \n",
            "1 -0.797724         -1.688276              False         False         False   \n",
            "2  0.056980          0.482364              False          True         False   \n",
            "3  0.569803         -0.835524              False         False         False   \n",
            "4 -0.968665          1.335116              False         False         False   \n",
            "\n",
            "   team_Mercedes  team_Red Bull  circuit_Silverstone  circuit_Spa  \n",
            "0           True          False                False        False  \n",
            "1          False           True                 True        False  \n",
            "2          False          False                False        False  \n",
            "3          False           True                False         True  \n",
            "4           True          False                 True        False  \n",
            "\n",
            "Skewness:\n",
            "age                    0.843199\n",
            "lap_time_seconds      -0.368189\n",
            "team_Aston Martin      3.000000\n",
            "team_Ferrari           1.619848\n",
            "team_McLaren           3.000000\n",
            "team_Mercedes          1.619848\n",
            "team_Red Bull          1.619848\n",
            "circuit_Silverstone    0.857143\n",
            "circuit_Spa            1.619848\n",
            "dtype: float64\n",
            "\n",
            "Preprocessing Completed Successfully\n"
          ]
        }
      ],
      "source": [
        "import pandas as pd\n",
        "import numpy as np\n",
        "\n",
        "from sklearn.preprocessing import StandardScaler\n",
        "\n",
        "data = {\n",
        "    'driver_name': ['Lewis Hamilton', 'Max Verstappen', 'Charles Leclerc', 'Sergio Perez', 'George Russell', 'Fernando Alonso', 'Carlos Sainz', 'Lando Norris', 'Esteban Ocon', 'Valtteri Bottas'],\n",
        "    'age': [38, 26, np.nan, 34, 25, 42, 29, 24, 27, 34],\n",
        "    'team': ['Mercedes', 'Red Bull', 'Ferrari', 'Red Bull', 'Mercedes', 'Aston Martin', 'Ferrari', 'McLaren', 'Alpine', 'Sauber'],\n",
        "    'circuit': ['Monaco', 'Silverstone', 'Monaco', 'Spa', 'Silverstone', 'Monaco', 'Spa', 'Silverstone', 'Monaco', 'Spa'],\n",
        "    'lap_time_seconds': [85.5, 82.1, 84.9, 83.2, 86.0, 85.1, 83.5, 82.9, 85.3, 150.2] # 150.2 is an intentional outlier\n",
        "}\n",
        "df = pd.DataFrame(data)\n",
        "\n",
        "print(\"Dataset Shape:\")\n",
        "print(df.shape)\n",
        "\n",
        "print(\"\\nColumns:\")\n",
        "print(df.columns)\n",
        "\n",
        "print(\"\\nDataset Info:\")\n",
        "print(df.info())\n",
        "\n",
        "print(\"\\nMissing Values:\")\n",
        "print(df.isnull().sum())\n",
        "\n",
        "df['age'] = df['age'].fillna(df['age'].mean())\n",
        "\n",
        "print(\"\\nDuplicates Before:\", df.duplicated().sum())\n",
        "\n",
        "df = df.drop_duplicates()\n",
        "\n",
        "print(\"Duplicates After:\", df.duplicated().sum())\n",
        "\n",
        "Q1 = df['lap_time_seconds'].quantile(0.25)\n",
        "Q3 = df['lap_time_seconds'].quantile(0.75)\n",
        "\n",
        "IQR = Q3 - Q1\n",
        "\n",
        "lower = Q1 - 1.5 * IQR\n",
        "upper = Q3 + 1.5 * IQR\n",
        "\n",
        "df = df[(df['lap_time_seconds'] >= lower) &\n",
        "        (df['lap_time_seconds'] <= upper)]\n",
        "\n",
        "print(\"\\nOutliers Removed\")\n",
        "\n",
        "print(\"\\nData Types:\")\n",
        "print(df.dtypes)\n",
        "\n",
        "df['age'] = df['age'].astype(int)\n",
        "\n",
        "df = pd.get_dummies(df,\n",
        "                    columns=['team','circuit'],\n",
        "                    drop_first=True)\n",
        "\n",
        "print(\"\\nAfter Encoding:\")\n",
        "print(df.head())\n",
        "\n",
        "scaler = StandardScaler()\n",
        "\n",
        "df[['age','lap_time_seconds']] = scaler.fit_transform(\n",
        "    df[['age','lap_time_seconds']]\n",
        ")\n",
        "\n",
        "print(\"\\nAfter Scaling:\")\n",
        "print(df.head())\n",
        "\n",
        "df = df.drop('driver_name', axis=1)\n",
        "\n",
        "print(\"\\nAfter Removing Driver Name Column:\")\n",
        "print(df.head())\n",
        "\n",
        "print(\"\\nSkewness:\")\n",
        "print(df.skew(numeric_only=True))\n",
        "\n",
        "df.to_csv(\"cleaned_f1_data.csv\",\n",
        "          index=False)\n",
        "\n",
        "print(\"\\nPreprocessing Completed Successfully\")"
      ]
    }
  ]
}